### PR TITLE
Removed duplicates ssl config in base.hcl.j2

### PR DESCRIPTION
**Pull request by kedai**

### CODE REVIEW

**Comment by Blefish** [comment]
There are duplicates in README.md as well as defaults/main.yml

**Review by batk0 — APPROVED** [review]

**Comment by ppacher** [comment]
Seems this one has been overlooked by me in #149 and by @sestegra in #150. I guess our both PRs can be closed in favor of this one when it get's merged

**Comment by cabbageman8** [comment]
Merge please :)

**Comment by lanefu** [comment]
Sorry for delay.    Feel free to @me if I'm not responsive to prs

**Pull request merged**
