### PR TITLE
Update nomad to 0.12.0

### PR DESCRIPTION
**Pull request by adawalli**
Addresses https://github.com/ansible-community/ansible-nomad/issues/97

### CODE REVIEW

**Comment by adawalli** [comment]
Browsing the agent config docs (https://github.com/hashicorp/nomad/blob/v0.12.0/website/pages/docs/configuration/index.mdx) I don't see any changes that need to be supported in the JINJA templates - @lanefu, let me know if you disagree or if this wasn't the best way to track down those changes.

**Comment by lanefu** [comment]
@adawalli were you about to test deploying with this update?

**Comment by adawalli** [comment]
I have been testing locally, yes. Feel free to merge or wait until next week - no rush either way.

**Comment by lanefu** [comment]
thanks for the updates @adawalli

**Pull request merged**
