### PR TITLE
Fix Nomad 1.7.x compatibility issue

### PR DESCRIPTION
**Pull request by sas1024**
Fix for https://github.com/ansible-community/ansible-nomad/issues/179 issue

### CODE REVIEW

**Comment by stoneus** [comment]
Perfect!

**Comment by madsboddum** [comment]
Looks good to me.

**Comment by rndmh3ro** [comment]
Does this still work with versions older than 1.7?

**Comment by sas1024** [comment]
@rndmh3ro yes, it works with all Nomad versions above 0.8.x

**Pull request merged**
