### PR TITLE
Add telemetry configuration possibilites

### PR DESCRIPTION
**Pull request by rndmh3ro**

### CODE REVIEW

**Comment by ducminhle** [comment]
Hello @rndmh3ro,
Do we need to add telemetry config? I see we have `nomad_config_custom`, I think we can add telemetry config in this variable.
Ex:

> consul_config_custom:
  telemetry:
    prometheus_retention_time: 24h
    disable_hostname: true

**Comment by ducminhle** [comment]
Hello @rndmh3ro,
Do we need to add telemetry config? I see we have `nomad_config_custom`, I think we can add telemetry config in this variable.
Ex:

> 
nomad_config_custom:
  telemetry:
    publish_allocation_metrics: true
    publish_node_metrics: true
    prometheus_metrics: true

**Comment by ducminhle** [comment]
Hello @rndmh3ro,
Do we need to add telemetry config? I see we have `nomad_config_custom`, I think we can add telemetry config in this variable.
Ex:

> nomad_config_custom:
  telemetry:
    publish_allocation_metrics: true
    publish_node_metrics: true
    prometheus_metrics: true

**Comment by rndmh3ro** [comment]
Hey @ducminhle,

we probably don't *need* this. However this way it's documented and easier to use.

**Comment by rndmh3ro** [comment]
Any reasons against merging this?

**Pull request merged**
