### PR TITLE
Update to Nomad 0.11.3

### PR DESCRIPTION
**Pull request by adawalli**
Addresses https://github.com/ansible-community/ansible-nomad/issues/84

### CODE REVIEW

**Comment by adawalli** [comment]
apologies for the trailing whitespace removals - I can remove that change if desired

**Comment by lanefu** [comment]
I merged, but if you have a chance to see if there's any new config vars to add since the version change that would be awesome

**Comment by adawalli** [comment]
I will try to make time to look into that - and of course, Nomad 0.12.0 left beta during this PR

**Comment by lanefu** [comment]
haha yeah I created #97 then realized this PR was here...

**Pull request merged**
