### PR TITLE
add enable_tls variable

### PR DESCRIPTION
**Pull request by imcitius**
More convenient way to add tls configuration block.

### CODE REVIEW

**Comment by rndmh3ro** [comment]
FYI: this is a breaking change.

If you previously defined only the tls certificates and now roll out nomad with this new configuration, TLS will be disabled.

**Comment by lanefu** [comment]
Crap

Should we rollback?

**Comment by imcitius** [comment]
I think initial role design wasn't good in this.
We can roll-back for now of course, and decide how to introduce this kind of changes in future?

**Comment by imcitius** [comment]
The purpose of this change was to separate operations of copy certificates to nomad config, and enabling TLS.
In my case certificates is put in place by another role, and copying files is not needed.
I'm pretty sure that this logic is more universal.

**Comment by rndmh3ro** [comment]
If this role uses semantic versioning, then everything is fine, since there's no new version released yet.

I'm in favor of this change, no questions here!

So I don't think anything should be done here.

**Pull request merged**
