### PR TITLE
Fix libcgroup dependency in Ubuntu 22.10 and newer

### PR DESCRIPTION
**Pull request by deltabweb**
I tried to run the role on Ubuntu 23.04 and got an error about the package `libcgroup1` not existing.
After checking https://launchpad.net/ubuntu/+source/libcgroup, it looks like the package was renamed to `libcgroup2` in Ubuntu 22.10
Both `libcgroup1` and `libcgroup2` seem to actually use the version 2 of libcgroup
I installed nomad successfully on Ubuntu 23.04 with this fix

### CODE REVIEW

**Comment by LordAro** [comment]
This is also an issue for debian 12, would be good if the same fix could be applied for that as per cgroup-bin below

**Comment by deltabweb** [comment]
@beechesII Sounds good, I have just updated the PR

**Review by beechesII — APPROVED** [review]
lgtm

tested with debian 12 - libcgroup2 will be installed and nomad installation via role works

**Comment by LordAro** [comment]
I actually had a different solution to this on my end - just remove libcgroupN from the deps list entirely

It's not used directly as far I can tell and it's pulled in by cgroups-bin / cgroups-tools anyway - just let the package manager worry about it

**Comment by beechesII** [comment]
> I actually had a different solution to this on my end - just remove libcgroupN from the deps list entirely
> 
> It's not used directly as far I can tell and it's pulled in by cgroups-bin / cgroups-tools anyway - just let the package manager worry about it

I'm not sure if every package manger will install libcgroup1 or libcgroup2 as a dependency. I only found information about this for debian. Therefore I think we shouldn't delete the installation for these packages.

**Comment by beechesII** [comment]
@bbaassssiiee @lanefu please have a look.

**Comment by beechesII** [comment]
@deltabweb can you please update your actual master. I added molecule tests for the role. Your PR should fix the tests for debian 12 and ubuntu 23.04.

**Pull request merged**
